import {imageFields} from '../lib/content'
import {defineArrayMember, defineField, defineType} from 'sanity'

export const homePage = defineType({
  name: 'homePage',
  title: "Domača stran",
  type: 'document',
  groups: [{name: 'basic', title: 'Osnovno', default: true}, {name: 'archive', title: 'Arhiv / pripravljeno v kodi'}],
  fields: [
    defineField({group: 'basic', 
      name: 'eyebrow',
      title: "Majhen napis nad naslovom",
      type: 'string',
    }),
    defineField({group: 'basic', 
      name: 'heroTitle',
      title: "Glavni naslov",
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({group: 'basic', 
      name: 'heroText',
      title: "Uvodni opis",
      type: 'text',
      rows: 4,
    }),
    defineField({fields: imageFields, readOnly: true, description: 'Spletna stran uporablja pripravljeno vsebino iz kode; to polje je ohranjeno zaradi obstoječih podatkov.', group: 'archive', 
      name: 'heroImage',
      title: "Stara uvodna slika",
      type: 'image',
      options: {hotspot: true},
    }),
    defineField({readOnly: true, description: 'Spletna stran uporablja pripravljeno vsebino iz kode; to polje je ohranjeno zaradi obstoječih podatkov.', group: 'archive', 
      name: 'heroVideoUrl',
      title: "Stari uvodni video",
      type: 'url',
    }),
    defineField({group: 'basic', 
      name: 'badges',
      title: "Poudarki ob naslovu",
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'label', title: 'Label', type: 'string'}),
            defineField({name: 'value', title: 'Value', type: 'string'}),
          ],
        }),
      ],
    }),
  ],
})