import {imageFields, cmsActivation} from '../lib/content'
import {defineArrayMember, defineField, defineType} from 'sanity'

export const servicePage = defineType({
  name: 'servicePage',
  title: 'Stran storitve',
  type: 'document',
  groups: [{name: 'basic', title: 'Osnovno', default: true}, {name: 'media', title: 'Fotografije in video'}, {name: 'content', title: 'Vsebina'}, {name: 'conversion', title: 'Povpraševanje'}, {name: 'seo', title: 'SEO'}],
  fields: [
    defineField({group: 'basic', 
      name: 'title',
      title: 'Naziv storitve',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({group: 'basic', 
      name: 'slug',
      title: 'URL slug',
      type: 'slug',
      options: {source: 'title', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({group: 'basic', 
      name: 'pageType',
      title: 'Tip strani',
      type: 'string',
      options: {
        layout: 'dropdown',
        list: [
          {title: 'Industrijski 3D tisk', value: 'industrial-printing'},
          {title: 'Velikoformatni 3D tisk', value: 'large-format-printing'},
          {title: 'FGF tisk iz granulata', value: 'fgf-printing'},
          {title: '3D skeniranje & reverse engineering', value: 'scanning-reverse'},
          {title: 'Obnova plastičnih kosov', value: 'plastic-restoration'},
          {title: 'Konstruiranje & 3D modeliranje', value: 'engineering-modeling'},
          {title: 'Prototipizacija', value: 'prototyping'},
        ],
      },
    }),
    defineField({group: 'basic', 
      name: 'eyebrow',
      title: 'Majhen napis nad naslovom',
      type: 'string',
    }),
    defineField({group: 'basic', 
      name: 'heroTitle',
      title: 'Glavni naslov',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({group: 'basic', 
      name: 'heroText',
      title: 'Uvodni opis',
      type: 'text',
      rows: 4,
    }),
    defineField({fields: imageFields, group: 'media', 
      name: 'heroImage',
      title: 'Glavna slika',
      type: 'image',
      options: {hotspot: true},
    }),
    defineField({group: 'content', 
      name: 'summaryCards',
      title: 'Kratke poudarjene kartice',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'label', title: 'Oznaka', type: 'string'}),
            defineField({name: 'value', title: 'Vrednost / tekst', type: 'string'}),
          ],
          preview: {
            select: {title: 'label', subtitle: 'value'},
          },
        }),
      ],
    }),
    defineField({group: 'content', 
      name: 'sections',
      title: 'Vsebinski sklopi',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'title', title: 'Naslov', type: 'string'}),
            defineField({name: 'text', title: 'Opis', type: 'text', rows: 4}),
            defineField({
              name: 'bullets',
              title: 'Točke',
              type: 'array',
              of: [defineArrayMember({type: 'string'})],
            }),
          ],
          preview: {
            select: {title: 'title'},
            prepare: ({title}) => ({title: title || 'Vsebinski sklop'}),
          },
        }),
      ],
    }),
    defineField({group: 'content', 
      name: 'suitableFor',
      title: 'Primerno za',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
    }),
    defineField({group: 'content', 
      name: 'notIdealFor',
      title: 'Ni najboljša izbira za',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
    }),
    defineField({group: 'content', 
      name: 'processSteps',
      title: 'Potek dela',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'title', title: 'Korak', type: 'string'}),
            defineField({name: 'text', title: 'Opis', type: 'text', rows: 3}),
          ],
          preview: {
            select: {title: 'title', subtitle: 'text'},
          },
        }),
      ],
    }),
    defineField({group: 'conversion', 
      name: 'ctaTitle',
      title: 'CTA naslov',
      type: 'string',
    }),
    defineField({group: 'conversion', 
      name: 'ctaText',
      title: 'CTA opis',
      type: 'text',
      rows: 3,
    }),
    defineField({group: 'seo', 
      name: 'seoTitle',
      title: 'SEO naslov',
      type: 'string',
      validation: (Rule) => Rule.max(70),
    }),
    defineField({group: 'seo', 
      name: 'seoDescription',
      title: 'SEO opis',
      type: 'text',
      rows: 3,
      validation: (Rule) => Rule.max(170),
    }),
  
    cmsActivation,
    defineField({name: 'replaceBody', title: 'Zamenjaj vsebinske sklope s spodnjo vsebino', type: 'boolean', group: 'content', initialValue: false, description: 'Vklopi samo, če želiš zamenjati pripravljene tehnične sklope. Uvod, slike v uvodu, navigacija in CTA ostanejo v obstoječi zasnovi. Če so sklopi prazni, se ohrani pripravljena vsebina.'}),
  ],
  preview: {
    select: {title: 'title', subtitle: 'slug.current', media: 'heroImage'},
  },
})
